name: Release Extension

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Optional existing tag to release (leave empty to rely on push trigger)'
        required: false
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
      RELEASE_TAG: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag != '' && github.event.inputs.tag || github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag != '' && github.event.inputs.tag || github.ref }}

      - name: Validate release tag
        if: ${{ !startsWith(env.RELEASE_TAG, 'v') }}
        run: |
          echo "::error::Release tag must start with 'v' (received '${RELEASE_TAG}')" && exit 1

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: xvfb-run -a pnpm test

      - name: Package extension
        run: pnpm exec vsce package --no-dependencies --out baseline-gate.vsix

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: baseline-gate-vsix
          path: baseline-gate.vsix

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: baseline-gate.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Visual Studio Marketplace
        if: ${{ env.VSCE_PAT != '' }}
        run: pnpm exec vsce publish --no-dependencies --pat "$VSCE_PAT"
