name: VSCE Package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  package:
    runs-on: ubuntu-latest
    env:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type-check tests
        run: pnpm run compile-tests

      - name: Build extension bundle
        run: pnpm run compile

      - name: Create VSIX artifact
        run: pnpm exec vsce package --no-dependencies --out baseline-gate.vsix

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: baseline-gate-vsix
          path: baseline-gate.vsix

      - name: Publish to Visual Studio Marketplace
        if: ${{ env.VSCE_PAT != '' }}
        run: pnpm exec vsce publish --pat "$VSCE_PAT"
